development:
  dialect: "mysql"
  database: "hogedb"
  host: {{ envOr "MYSQL_HOST" "127.0.0.1"  }}
  port: {{ envOr "MYSQL_PORT" "3306"  }}
  user: {{ envOr "MYSQL_USER"  "root"  }}
  password: {{ envOr "MYSQL_PASSWORD"  "root"  }}
  encoding: "utf8mb4_general_ci"

ci:
  dialect: "mysql"
  database: "cihogedb"
  host: {{ envOr "MYSQL_HOST" "127.0.0.1"  }}
  port: {{ envOr "MYSQL_PORT" "3306"  }}
  user: {{ envOr "MYSQL_USER"  "root"  }}
  password: {{ envOr "MYSQL_PASSWORD"  ""  }}
  encoding: "utf8mb4_general_ci"
