version: '3.1'

services:

  mysql:
    container_name: hoge-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb_file_format=Barracuda --innodb_large_prefix=1 --explicit_defaults_for_timestamp=1 --general_log=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hogedb
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      localnet:
        aliases:
          - local-mysql
networks:
  localnet:
